format = '${custom.tab}$all'

[custom.tab]
description = 'The current tab in the tab terminal multiplexer'
command = 'tab --starship'
when = 'tab --starship'
shell = ['sh']
style = 'bold blue'
format = '[$output]($style)'

[custom.kakoune]
symbol = 'ğŸˆ'
command = 'kcr prompt'
when = 'kcr prompt'
shell = ['sh']
description = 'The current Kakoune session and client'
style = 'green'
format = '[$symbol $output]($style)'
